version: '3.8'

services:
  web:
    image: php:8.2-fpm
    container_name: php-web
    volumes:
      - ./web:/var/www/html
    networks:
      - webnet

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
s